### ISSUE TITLE
feature: label/name visibility

### ISSUE THREAD

**Issue by bheadwhite** [cbochs/grapple.nvim#105]
name visibility as virtual text at the end of a file path requires some effort to parse, especially as the paths get bigger. looking for a feature where we can pass in a custom label for the tag and have that displayed instead of the path.

currently using the `name` option to get around this. displaying it as virtual text all the way on the right is a little bit easier... it would be nice if it was just at the left near the numbers

**Comment by cbochs** [comment]
I think this is a good point. I've gone ahead and added a couple experimental rendering styles to the tag window. Please try it out and let me know what you think! The working branch is `tag_window_styles`. It's configurable with the following settings:

```lua
require("grapple").setup({
    ---Where a tag's name (if present) should be placed in the Tags Window
    ---@type "start" | "end"
    tag_name = "start",

    ---How a tag's path should be displayed in the Tags Window
    ---
    ---Using "relative" will show the path relative to the user's current
    ---working directory
    ---
    ---Using "basename" will show the path's basename with a directory hint
    ---when more than one tag share the same basename
    ---@type "basename" | "relative"
    tag_style = "relative",
})
```

### Example Screenshots

#### Using `relative` and `start`

<img width="1059" alt="image" src="https://github.com/cbochs/grapple.nvim/assets/2467016/2543b790-42fb-42d5-9d00-618e03510871">

#### Using `relative` and `end`

<img width="1059" alt="image" src="https://github.com/cbochs/grapple.nvim/assets/2467016/738d3e03-dc44-42b4-91d7-f9dff402164b">

#### Using `basename` and `start`

<img width="1059" alt="image" src="https://github.com/cbochs/grapple.nvim/assets/2467016/37d99c82-5d26-4e09-a79f-cad16be5f39d">

#### Using `basename` and `end`

<img width="1059" alt="image" src="https://github.com/cbochs/grapple.nvim/assets/2467016/a4d08a6a-8fd5-4b3a-92d0-e7d7b9e74d03">

**Comment by cbochs** [comment]
@bheadwhite I've added two new settings that you may find useful.

- `name_pos`: allows you to define where a tag's name should go
- `style`: allows you to define how a tag's path should be rendered

For more information, please read the [Settings](https://github.com/cbochs/grapple.nvim?tab=readme-ov-file#settings) section.

Thanks! 🙂
