### ISSUE TITLE
`Tag.find` equivalent in new api

### ISSUE THREAD

**Issue by vtrvtr** [cbochs/grapple.nvim#111]
Hi, I used to have the following function 

```lua
function file_name_from_tag(key)
  local tag = require("grapple").find { key = key }
  if tag == nil then return string.format("Mark %s", key) end
  return string.format("Mark %s %s", key, truncate_path(tag["file_path"]))
end
```

I used this to display the current tag in various places (telescope/whichkey). It seems this function was removed in the new update. Is there a way I can do something equivalent in the new api? 

Thanks, awesome plugin.

**Comment by cbochs** [comment]
I'm happy to add back something like `Grapple.find`. However, would something that returns all tags for a given scope work for you? Right now the following function is used for Grapple's default telescope integration:

```lua
---Return the tags for a given scope. Used for integrations like telescope
---@param opts? { scope?: string }
---@return grapple.tag[] | nil, string? error
require("grapple").tags(opts)
```

Where `grapple.tag` is

```lua
---@class grapple.tag
---@field path string absolute path
---@field name string | nil (optional) tag name
---@field cursor integer[] (1, 0)-indexed cursor position
```

**Comment by vtrvtr** [comment]
Yes, that works fine. Thanks. Please close this issue if you prefer to not implement it.

**Comment by cbochs** [comment]
@vtrvtr added `Grapple.find` 🙂 I am curious, however, what was your use-case for whichkey?

**Comment by vtrvtr** [comment]
Awesome, thanks 

I used it in which key for this: 

![image](https://github.com/cbochs/grapple.nvim/assets/9109280/fdae29aa-a07e-4f07-9c08-ee5368b0d2c4)

I use grapple more like vanilla vim marks, so in which key I can see which file is marked with that particular name

**Comment by cbochs** [comment]
Very neat!
