### ISSUE TITLE
Add scope customization for the lualine component

### ISSUE THREAD

**Issue by ColinKennedy** [cbochs/grapple.nvim#136]
The new lualine component is excellent but it assumes the user's scope. If they user prefers working in `"git_branch"`, for example, the display won't show them.

I'm not sure how best to integrate that into Lualine but if it's too much trouble, perhaps just a small API wrapper for us to make a custom lualine component would be alright

**Comment by cbochs** [comment]
I'm a little confused here. Would you mind sending your configuration? The statusline should use the scope you set during `Grapple.setup`. If you setup grapple like the following:

```lua
require("grapple").setup({
    scope = "git_branch"
})
```

Then the lualine component should use `"git_branch"`. If it doesn't then that is a bug.

**Comment by ColinKennedy** [comment]
My bad, I wasn't aware that a person could set `scope` during setup and have that propagate to other areas of the code. It works! I'll close this
