### ISSUE TITLE
feature: Statusline caching and custom functions

### ISSUE THREAD

**Issue by abeldekat** [cbochs/grapple.nvim#147]
### Did you check the docs?

- [X] I have read the Grapple docs

### Is your feature request related to a problem? Please describe.

Hello @cbochs,

Recently, I wrote `harpoonline`, around the same time `grapple` incorporated its `statusline`.

I have been using `grapple` for a week now and it's a perfect replacement for `harpoon`. I also like the paradigm and the additional features.

Based on `harpoonline`, I refactored and wrote [grappleline](https://github.com/abeldekat/grappleline).

The plugin adds the following to grapple's builtin `statusline`:

- Caching: Only recomputes the last line when needed
- An "on_update" callback, triggering any consumer to refresh
- Additional builtin and custom functions to render the information in various ways.

Would you be interested in a PR? I think that the additional functionality would fit very nicely into `grapple`.

I would appreciate your opinion!

### Describe the solution you'd like

...

### Describe alternatives you've considered

...

**Comment by cbochs** [comment]
Hey @abeldekat, grappleline looks great! A few questions:

> Caching: Only recomputes the last line when needed

Are you experiencing any measurable latency when using the default grapple.nvim statusline? Scope themselves are already cached, which should reduce most of the overhead of recomputing the statusline value.

> An "on_update" callback, triggering any consumer to refresh

Grapple [already executes](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/tag_manager.lua#L59-L62) a `GrappleUpdate` autocommand when a change is made. Would this suffice for your usecase?

> Additional builtin and custom functions to render the information in various ways.

There are a [few methods available](https://github.com/cbochs/grapple.nvim/tree/main?tab=readme-ov-file#statusline) to customize your own statusline if you want to. Is there any information that you think a user would need to build their statusline which is not already provided by Grapple?

**Comment by cbochs** [comment]
> On a side note: I had some problems using the second `lualine` example:
> 
> ```lua
> require("lualine").setup({
>     sections = {
>         lualine_b = {
>             { require("grapple").name_or_index,  cond = require("grapple").exists }
>         }
>     }
> })
> ```

This appears to have been incorrect. I've updated the README to fix this. Thanks for bringing it up!

> For my usecase, the plugin would be redundant when grapple would have:
> 
> 1. A `grapple.statusline` class caching the line, rebuilding on `GrappleUpdate` and `GrappleChangeScope`
> 
> 1. A function hook in settings-statusline, to transform data into a custom line representation.
> 
> 1. An on-update hook in settings-statusline, perhaps defaulting to `lualine`. The on-update hook is important when using keystrokes that don't affect the buffer. For example, on `grapple.use_scope`. I think `lualine` has an autoupdate mechanism. Even then, there could be a slight delay before the name of the scope is updated.

I added an event called `GrappleScopeChanged` which will trigger when a user changes their scope. There is now also a [global app cache](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/app.lua#L37) that _could_ be used for caching the statusline in [`Grapple.statusline`](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple.lua#L378)

If you'd still interested, I would be happy to take a look at a PR which would add the last two points you mentioned, just making sure it keeps the current default behaviour 🙂

**Comment by abeldekat** [comment]
That's great! I will propose a PR, hopefully this week.

**Comment by abeldekat** [comment]
@cbochs, FYI, I started working on the PR. Hope to send a first draft soon.
