### ISSUE TITLE
QoL change: when jumping to the file you are currently on, it shouldn't change the view

### ISSUE THREAD

**Issue by ArjunSahlot** [cbochs/grapple.nvim#150]
### Did you check docs and existing issues?

- [X] I have read the Grapple docs
- [X] I have searched the existing issues of Grapple

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Ubuntu 22.04

### Describe the bug

Whenever you jump to the file you are currently on, it jumps to it causing it to change the view and centers the cursor. Since the view gets changed I always feel like I'm in a different file when in reality I'm not. There should be a check for if the file you are jumping to is the same as the file you are in, in which case it shouldn't jump.

### Steps To Reproduce

1. Jump to the file you are currently in
2. View changes (gets centered)

### Expected Behavior

Shouldn't change the view at all.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "cbochs/grapple.nvim"
  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by ArjunSahlot** [comment]
This isn't a bug but had to use this tag as I couldn't find a fitting one.

**Comment by cbochs** [comment]
Have you tried setting the `command` in the [settings](https://github.com/cbochs/grapple.nvim?tab=readme-ov-file#settings)?

```lua
    ---Default command to use when selecting a tag
    ---@type fun(path: string)
    command = vim.cmd.edit,
```

The default is `vim.cmd.edit`, but maybe something like this work for you?

```lua
require("grapple").setup({
    command = function(path)
        if vim.api.nvim_buf_get_name(0) ~= path then
            vim.cmd.edit(path)
        end
    end
})
```

**Comment by ArjunSahlot** [comment]
Wow that's really extensible! Unfortunately that command didn't work. I'm assuming `vim.api.nvim_buf_get_name(0)` returns something similar to but not exactly `path`. Would you mind having another go at it because I'm not super familiar with all the various `vim.api` functions.

**Comment by cbochs** [comment]
Ah, I forgot that I sent a shortened version of the tag's path to the command. I've pushed 34b8f4728294058e9fdad116fd21f72feb66ab73 which should now send the absolute path instead. The above code snippet should work for you if you grab the latest changes.

Also, you should checkout `:h vim.api`, there's lots of fun stuff to learn there 😉 

As a tip, you can always run a quick lua snippet and print it's output by prepending `lua=` to a command. For example, the following gets the (current) buffer's name:

```
lua=vim.api.nvim_buf_get_name(0)
```

**Comment by ArjunSahlot** [comment]
Thanks a lot! Yup I know a few of these tips to find out what functions do quickly. I'm actually a fellow neovim plugin developer (global-registers.nvim if you'd like to check it out in my github profile), but I'm also fairly new to the neovim ecosystem (4-5 months). By the way, this is an awesome plugin and your responsiveness really makes it 10 times better. Thatnks for your contributions to this community!

**Comment by cbochs** [comment]
Happy to help, and thank you for the kind words.

Also, that's a neat little plugin, nice work!
