### ISSUE TITLE
bug: calling open_tags with global scope throws error

### ISSUE THREAD

**Issue by bheadwhite** [cbochs/grapple.nvim#161]
### Did you check docs and existing issues?

- [X] I have read the Grapple docs
- [X] I have searched the existing issues of Grapple

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS Sonoma 14.4.1

### Describe the bug

![CleanShot 2024-04-29 at 21 22 37@2x](https://github.com/cbochs/grapple.nvim/assets/26074150/d603fd70-bc0f-480a-b5ec-83f9abb124d1)
upon calling open_tags with global scope, i get this error

### Steps To Reproduce

open global tags, i am using named tags..

### Expected Behavior

no thrown error

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "cbochs/grapple.nvim"
  -- add any other plugins here
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by cbochs** [comment]
Hi @bheadwhite, thanks for bringing this up. Taking a look, I may have accidentally used a v0.10.0 feature (inline extmarks) in one of the more recent commits. With v0.10.0 recently released, this should be fixed by updating to that version.

Please let me know if updating doesn't resolve the issue!

**Comment by bheadwhite** [comment]
@cbochs hey, after upping to latest neovim version its now working as expected. thanks so much!
