### ISSUE TITLE
bug: unable to change scope via <S-CR> in scopes window

### ISSUE THREAD

**Issue by kucaiyi** [cbochs/grapple.nvim#163]
### Did you check docs and existing issues?

- [X] I have read the Grapple docs
- [X] I have searched the existing issues of Grapple

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

linux

### Describe the bug

Not sure if it's just me:
I am unable to change scope in the scopes window via `<S-CR>`; however, scope can be changed via use_scope api

### Steps To Reproduce

1. open scopes window
2. hit `<S-CR>`
3. hit `<->` to move back to the scopes window
4. current scope is unchanged

### Expected Behavior

4. the current scope should be changed accordingly

**Comment by lushcluejug** [comment]
I'm also experiencing this exact same issue.

**Comment by kucaiyi** [comment]
Fixed by adding the below to alacritty

```toml
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"
```

[explanation](https://stackoverflow.com/questions/16359878/how-to-map-shift-enter)
