### ISSUE TITLE
feature: add the ability to switch back to the previous tag with the same binding

### ISSUE THREAD

**Issue by mohammad-amin-khajeh** [cbochs/grapple.nvim#169]
### Did you check the docs?

- [X] I have read the Grapple docs

### Is your feature request related to a problem? Please describe.

Sometimes I just want to have a quick peek at for example tag x and go back to the previous tag(let's call it tag y)
So I press `<A-b>` to go the tag x, and after I check tag x I press `<A-b>` again to go to the previous/last tag, in this case tag y.
it would be so convenient to have this feature in grapple.nvim, to be able to go to a tag with a specified shortcut and come back with the same shortcut.

### Describe the solution you'd like

My suggestion is to have a boolean field in the opts table that enables this feature, i3wm has such feature and they call it `auto_back_and_forth` so maybe you can call it that or something like `quick_switch` or something else along those lines.

### Describe alternatives you've considered

For now I use the bindings I've specified for each tag to go to that tag and use a different binding to go to the last/previous tag.

**Comment by will-lynas** [comment]
Do you specifically want it to go back to the last _tag_, or just to the last buffer?

My workflow for this would be `<A-b>` to jump to the tag, then `<C-^>` to jump back to the last buffer.

It might be nice if the `select` function did have a `quick_switch` option, which when enabled would allow you to do `<A-b>` twice and have the same behaviour as above.

**Comment by mohammad-amin-khajeh** [comment]
I only use grapple to tag my main files and switch to them so switching to the last buffer is fine.

I'll look into the source code tomorrow and see if I can implement something myself.

**Comment by will-lynas** [comment]
Did you get anywhere with this?

**Comment by mohammad-amin-khajeh** [comment]
Oh yeah I forgot about this issue sorry for not replying

I did not edit the source code directly but found a hacky solution using the provided API

Here's how I achieved the desired behavior(in lazy.nvim's `keys` table where I declare and install grapple.nvim, you can just use `vim.keymap.set()` instead if you want):
```lua
    keys = {
      { "<leader>a", "<cmd>Grapple toggle<cr>", desc = "grapple toggle a file" },
      { "<C-e>", "<cmd>Grapple toggle_tags<cr>", desc = "grapple toggle tags menu" },

      {
        "<leader>1",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 1 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=1")
          end
        end,
        desc = "grapple select first tag",
      },

      {
        "<leader>2",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 2 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=2")
          end
        end,
        desc = "grapple select second tag",
      },

      {
        "<leader>3",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 3 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=3")
          end
        end,
        desc = "grapple select third tag",
      },

      {
        "<leader>4",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 4 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=4")
          end
        end,
        desc = "grapple select fourth tag",
      },

      {
        "<leader>5",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 5 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=5")
          end
        end,
        desc = "grapple select fifth tag",
      },

      {
        "<leader>6",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 6 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=6")
          end
        end,
        desc = "grapple select sixth tag",
      },

      {
        "<leader>7",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 7 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=7")
          end
        end,
        desc = "grapple select seventh tag",
      },

      {
        "<leader>8",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 8 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=8")
          end
        end,
        desc = "grapple select eighth tag",
      },

      {
        "<leader>9",
        function()
          if
            require("grapple").exists()
            and require("grapple").find({ index = 9 }) == require("grapple").find({ buffer = 0 })
          then
            vim.cmd.norm("")
          else
            vim.cmd("Grapple select index=9")
          end
        end,
        desc = "grapple select ninth tag",
      },
    },
```

I'm basically checking whether the current buffer is tagged and if so move onto the next condition, which is whether tag x is equivalent to the tag at current buffer(buffer 0), if that's the case I send a `ctrl-^` binding which switches to the last buffer, if not I simply switch to that buffer.

There is one minor problem, or better say an edge case though.
And that is if the first opened buffer is the one you are trying to switch to(opening the file that's tagged x as your first file and pressing `<leader>x` to switch to the buffer before that, which doesn't exist).
But I don't really don't think that's a common issue so I didn't bother with it.

Anyways I'll close the issue since I'm satisfied with the result.
