### ISSUE TITLE
feature: option for removing the footer

### ISSUE THREAD

**Issue by k14lb3** [cbochs/grapple.nvim#171]
### Did you check the docs?

- [X] I have read the Grapple docs

### Is your feature request related to a problem? Please describe.

Window looks bulky.

### Describe the solution you'd like

```
require("grapple").setup({
  win_opts = {
        ...,
        footer = nil, -- Can either be empty string (`''`) or `nil`,
    },
})
```

### Describe alternatives you've considered

None.

**Comment by cbochs** [comment]
@k14lb3 This should be possible now. To do so, set `footer = ""` in the settings
