### ISSUE TITLE
[FR] send command like harpoon

### ISSUE THREAD

**Issue by bangedorrunt** [cbochs/grapple.nvim#19]
I'm not sure this is out of scope of this project. But it would be great to be able to send saved project commands to Tmux panes and/or Neovim built-in terminals

**Comment by cbochs** [comment]
Hey, thanks for the feature request!

The goal of this project is more aimed at file tagging so tmux support is not really in the roadmap as of right now. 

However, I might consider exploring that avenue after I've had the chance to stabilize a v0.x candidate that's a little more feature complete.

If there're any other features you'd like to see in grapple, please let me know!

**Comment by cbochs** [comment]
Revisiting this since Grapple has matured a bit. Sending commands is a feature that I don't plan on adding. There are great plugins like [tmux.nvim](https://github.com/aserowy/tmux.nvim) that integrate nicely with tmux for these kind of operations.
