### ISSUE TITLE
add Resession.nvim support

### ISSUE THREAD

**Issue by RaafatTurki** [cbochs/grapple.nvim#2]
Awesome plugin!

[resession.nvim](https://github.com/stevearc/resession.nvim) is a neovim plugin meant to take away the burden of persisting data without the hassle of dealing with `:mksession` or writing/parsing json files manually.

it's highly extensible, designed with plugin-data in mind and is already being used for big plugins such as `aerial.nvim` and `overseer.nvim`.

One of the reasons why I stopped using harpoon is because of `harpoon.json` (I've talked more about this in its own [issue](https://github.com/ThePrimeagen/harpoon/issues/177))

lmk what you think!

**Comment by cbochs** [comment]
I like the idea of adding optional support for resession.nvim. it appears to be a good backend for saving state, so I wouldn't have any problems giving the choice. 

I'll take a look at its implementation when I get the chance here soon. 

Thanks for the suggestion!

**Comment by RaafatTurki** [comment]
That sounds great!, one more thing regarding resession, it already [saves and restores the cursor position](https://github.com/stevearc/resession.nvim/issues/2) It would be pointless if grapple also did that.

I suggest a config option to disable this feature.

**Comment by cbochs** [comment]
> one more thing regarding resession, it already https://github.com/stevearc/resession.nvim/issues/2 It would be pointless if grapple also did that.

While that may be true, marks may exist for files that don't have a valid buffer. Grapple could opt to defer cursor tracking to resession, but I think this may be unnecessary coupling. It is probably better to keep cursor state separate for now.

I've added preliminary support for resession. Feel free to try it out with the branch `feat_integrations_resession` 🙂 

To enable grapple as an extension:

```lua
require("grapple").setup({
    integrations = {
        resession = true
    }
})

require("resession").setup({
    extensions = {
        grapple = {}
    }
})
```

You may need to pass in `enable_in_tab = true` into `grapple = { ... }`, but I feel like that shouldn't be necessary.
