### ISSUE TITLE
(feat)re-ordering: allow to change tag orders via the popup window

### ISSUE THREAD

**Issue by gjeusel** [cbochs/grapple.nvim#22]
Hey there 👋 

I love your plugin for keeping things simple and straightforward !

I just miss a few features I'll try to list down below.
The main one being the one in the title of this issue.

#### 1) Log filepath

I believe the log file should be stored at `vim.fn.stdpath("cache") .. "/" .. "grapple.log"` and not `vim.fn.stdpath("data") .. "/" .. "grapple.log"`. Like `null-ls`, `mason.nvim` or even `packer.nvim` does.

#### 2) Tag order edition from the popup

I would love to be able to edit the order directly modifying the popup window.
Either by moving around the entires lines and considering the new line order to be the future indexes.
Either by modifying the index of each line upfront.
And I guess pressing enter to the commit the change (without opening the buffer tagged if the popup was modified), or quitting to cancel modifications.

That would rock !

#### 3) Add a FileType to the popup buffer

Automatically setting the filetype of the popup buffer to something like `grapple` would be awesome, as it would open up doors for customisation.

Et voilà,
Let me know what you think about it !

**Comment by cbochs** [comment]
Hello!

These are excellent suggestions.

> 1) Log filepath

I agree. This is a good change that I've been meaning to do. Glad to see you already have an open PR (#25) for it.

> 2) Tag order edition from the popup

This was a feature I was hoping to add as well. Glad to see someone else would find this useful! Will discuss more in #26.

> 3) Add a FileType to the popup buffer

This would be a good customization QoL feature 🙂 Thanks for opening #23 to address it

Thanks for taking the initiative on these!

**Comment by cbochs** [comment]
Resolved by #23, #25, #27
