### ISSUE TITLE
Enhancment: A function that outputs current mark status of file ?

### ISSUE THREAD

**Issue by A-Lamia** [cbochs/grapple.nvim#30]
Wandering if there could be an API for people that use other status lines (heirline) so i could check if there is a tag on the buffer.

**Comment by cbochs** [comment]
Ah! This API exists. There are a couple undocumented features (which I should document). A file tag can be checked with:

```lua
---@param opts Grapple.Options
---@return boolean
require("grapple").exists({ buffer = 0 })
```

or, if you want the key for a (possibly) tagged file:

```lua
---@param opts Grapple.Options
---@return Grapple.TagKey | nil
require("grapple").key({ buffer = 0 })
```

**Comment by cbochs** [comment]
I've added a follow-up story to document this information so you are able to find it more easily next time 🙂 I am assuming the above is what you were looking for, but in the case that it is not please feel free to re-open this issue and continue the discussion

**Comment by A-Lamia** [comment]
@cbochs 
It was thanks!
already added what i wanted to my status line, so everything is ready to go once paths get fixed xD.

![image](https://user-images.githubusercontent.com/6450181/202841774-bed53efb-a89a-4c83-8a41-21bc8acd15eb.png)

![image](https://user-images.githubusercontent.com/6450181/202841804-634bf5c7-054f-486d-a929-592a890c1198.png)
