### ISSUE TITLE
Support Windows style paths 

### ISSUE THREAD

**Issue by cbochs** [cbochs/grapple.nvim#31]
Currently, grapple.nvim assumes unix-style (`/`) paths. This assumption breaks for Windows users, where:
1. paths are delimited by a backward slash `\`
2. absolute paths start with a drive letter (e.g. `C:\\`)

**Comment by cbochs** [comment]
@A-Lamia I've started some initial work towards supporting Windows file paths. Feel free to check it out on the branch: `fix_support_windows_paths`. Note: plenary.nvim has been added as a dependency.

Compare: [`main .. fix_support_windows_paths`](https://github.com/cbochs/grapple.nvim/compare/fix_support_windows_paths)

**Comment by A-Lamia** [comment]
Gave it a try seems you got `GrappleTag` working and the output to the json is correct.

Still broken
- [ ] GrapplePopup
![image](https://user-images.githubusercontent.com/6450181/202849909-b46ad365-6bd2-4bb3-b125-7d18efc6acf9.png)
- [ ] GrappleToggle 
Untag part of toggle silent fails on current buffer explisitly setting `GrappleToggle key =n` works how ever
- [ ] GrappleUntag
Same as above

**Comment by cbochs** [comment]
A couple things to unpack here:

? GrapplePopup

Since there are two different kinds of popup's available, `:GrapplePopup` takes in an argument of either `tags` or `scopes`. Try using `:GrapplePopup tags` instead. See: [README#tag-popup-menu](https://github.com/cbochs/grapple.nvim#tag-popup-menu)

> GrappleToggle

A couple questions:
1. Does `:GrappleTag` work to tag the current buffer?
2. Does `:GrappleToggle key=n` work for both tagging and untagging?

I've gone ahead made a couple more changes to the `fix_support_windows_paths` branch. I would suggest changing the log level to `debug`. Then maybe we can get a little more insight into the silent failures.

```lua
require("grapple").setup({
    log_level = "debug"
})
```

**Comment by A-Lamia** [comment]
@cbochs, played around with master, discovered some things.

#### A couple answers:
1. `:GrappleTag` does work` to tag the current buffer.
2. `:GrappleToggle key=n` works for tagging and untagging.

#### Some side issues i found:
- If you use `:GrappleToggle key=0` it will tag with 0 but not untag. (No log or error message)

- `:GrapplePopup tags` and `scopes` both return `E488: Trailing characters: tags` or `scopes`;
`:lua require("grapple").popup_scopes()` and `popup_tags()` work fine.

**Comment by cbochs** [comment]
>     * `:GrapplePopup tags` and `scopes` both return `E488: Trailing characters: tags` or `scopes`;
>       `:lua require("grapple").popup_scopes()` and `popup_tags()` work fine.

Nice catch! I've fixed this in 65de44abb66f93259a0c9f433a9c66527c53aad5 and rebased the `fix_support_windows_paths` branch to pull in that commit.

> #### Some side issues i found:
> 
>     * If you use `:GrappleToggle key=0` it will tag with 0 but not untag. (No log or error message)

This is an edge case I did not consider - but appears to have a few associated bugs, so great find!  Lua is 1-indexed which means numbered keys should probably be required as positive. Although that constraint "feels" a little arbitrary, but might be alright to impose for now.

I tried `:GrappleTag key=0` followed by `:GrappleUntag key=0` and ended up with 10 new tags (indices 1 to 11) which was very strange behaviour indeed. Going to have to look into this.

>     1. `:GrappleTag` does work to tag the current buffer.
>     2. `:GrappleToggle key=n` works for tagging and untagging.

Glad at least a couple things are working as intended 🙂

**Comment by cbochs** [comment]
As a follow-up to the `key=0`, I think a possible compromise would be to clamp the input tag between `[1, #tags + 1]`, inclusive. Then, any tag in the range of (-inf, 1] is fixed to an index of `1` and any tag in the range [#tags + 1, inf) is fixed to an index of `#tags + 1`. I made this change to the `fix_support_windows_paths` branch with 97734f19d2da261c6507b9c9b681bab0b375a7d0

**Comment by A-Lamia** [comment]
Nice i tried everything out seems to be working.

If you use `:GrappleTag key=0` the tag will be 0 then on the same buffer follow with `:GrappleToggle` and it will update correctly say if you had 3 tags it will be 4.

**Comment by cbochs** [comment]
Awesome. I fixed a couple more issues with some unexpected differences between `:GrappleToggle` and it's API equivalent of `require("grapple").toggle()`.

Created a PR here: https://github.com/cbochs/grapple.nvim/pull/34

Feel free to pull in the latest commit(s) and give it a go. If you find anything, let me know! If nothing pops up, I'll go ahead with the merge.

**Comment by A-Lamia** [comment]
Tested everything and tried to break it, everything seems ready to go. nice work!

**Comment by cbochs** [comment]
@A-Lamia All merged. Thanks for all of your help with testing these changes!

**Comment by A-Lamia** [comment]
@cbochs glad to help!
