### ISSUE TITLE
feat(tags): periodically sync tag state

### ISSUE THREAD

**Issue by cbochs** [cbochs/grapple.nvim#33]
The persisted tag state should try to stay up-to-date with a nvim session's local state. Provide the ability to automatically update the tags state in the background periodically or on command.

**Comment by A-Lamia** [comment]
not sure if it's possible but could be an ok to update tag on buffer close or write some times im reading through a large file but haven't actually modified anything would be nice if when i save or close the buffer it updates the last cursor position.

**Comment by cbochs** [comment]
This is definitely possible. I think the start to this feature would be to develop something like a `require("grapple").sync` function which asynchronously syncs the state between the `grapple.json` and the current session's local stata. Then _where_ this method is called (on `VimLeave`, `BufExit`, every 60 seconds, etc.) becomes just a matter of what default choices are best to present the user.

**Comment by akinsho** [comment]
Not sure if this exactly fits into this issue, but I've noticed as well that tag can go out of sync if there are filesystem changes so you can end up with a tag referencing a renamed or deleted file. Seems like in this case when the sync occurs it should also remove outdated/invalid tags

**Comment by cbochs** [comment]
Going to close this as the [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite) I'm working on should address this issue.
