### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by A-Lamia** [cbochs/grapple.nvim#41]
Just quickly tried to change the resolver but it's still throwing an error 

```lua
  scope = function()
    -- Attempt to use a git directory as the project scope
    local root_files = vim.fs.find(".git", { upward = true })
    if #root_files > 0 then
      return vim.fs.dirname(root_files[1])
    end
    -- Fallback to "lsp", which will fallback to "directory" if not found
    return require("grapple.scope").resolvers.lsp
  end
```

also tried

```lua
  scope = function()
    require("grapple.scope").fallback({
      require("grapple.scope").resolvers.lsp,
      require("grapple.scope").root(".git"),
      require("grapple.scope").resolvers.static
    })
  end
```

Not sure what im doing wrong.
![image](https://user-images.githubusercontent.com/6450181/204140062-94fa15d9-e1d1-41f6-804b-1e3ea26d3806.png)

**Comment by cbochs** [comment]
The scope passed in should now be a [scope resolver](https://github.com/cbochs/grapple.nvim#grapplescoperesolver). The last example was close, should just be without the surrounding `function`:

```lua
require("grapple").setup({
    scope = require("grapple").fallback({
        require("grapple").resolvers.lsp,
        require("grapple").resolvers.git,
        require("grapple").resolvers.static,
    })
})
```

**Comment by A-Lamia** [comment]
@cbochs 
seems something is wrong
![image](https://user-images.githubusercontent.com/6450181/204140586-7236ab07-7dd9-4562-866f-5d333b8473be.png)

**Comment by cbochs** [comment]
Yup. You're right. That's because I used `grapple` not `grapple.scope`

```lua
require("grapple").setup({
    scope = require("grapple.scope").fallback({
        require("grapple.scope").resolvers.lsp,
        require("grapple.scope").resolvers.git,
        require("grapple.scope").resolvers.static,
    })
})
```

**Comment by A-Lamia** [comment]
an other error,
![image](https://user-images.githubusercontent.com/6450181/204140816-144f8d3c-a790-4992-95c8-fc85da105aa9.png)

**Comment by cbochs** [comment]
That is odd. Can you let me know if the following works?

```lua
require("grapple").setup({ scope = "static" })
```

**Comment by A-Lamia** [comment]
Yep that works fine

**Comment by cbochs** [comment]
How about this command:

```
lua =vim.lsp.get_active_clients({ bufnr = 0 })[1].config
```

**Comment by A-Lamia** [comment]
Seem to get an output,
```lua
{
  _on_attach = <function 1>,
  autostart = true,
  capabilities = {
    callHierarchy = {
      dynamicRegistration = false
    },
    textDocument = {
      codeAction = {
        codeActionLiteralSupport = {
          codeActionKind = {
            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" }
          }
        },
        dataSupport = true,
        dynamicRegistration = false,
        isPreferredSupport = true,
        resolveSupport = {
          properties = { "edit" }
        }
      },
      completion = {
```

**Comment by cbochs** [comment]
Hm. I just made a commit (https://github.com/cbochs/grapple.nvim/commit/c3d27d77c3c3c821a3d201494cb59634d08b0bcd) that separates out two resolvers that don't have builtin fallbacks: `git_fallback` and `lsp_fallback`. Can you try:

```lua
require("grapple").setup({
    setup = require("grapple.scope").fallback({
        require("grapple.scope").resolvers.lsp_fallback,
        require("grapple.scope").resolvers.git_fallback,
        require("grapple.scope").resolvers.static
    })
})
```

**Comment by A-Lamia** [comment]
There was an error at first but after a resync everything seems to be working fine now.

**Comment by A-Lamia** [comment]
Will close this now, thanks for the assist :D

**Comment by cbochs** [comment]
Great! I'll make sure to edit the post I made in the Breaking Changes #39 issue to note this. Thanks for the help diagnosing

**Comment by cbochs** [comment]
As a final note, I've updated both the [Tag Scopes](https://github.com/cbochs/grapple.nvim#tag-scopes) and [`grapple.scope#fallback`](https://github.com/cbochs/grapple.nvim#grapplescopefallback) sections in the README to mention these special scope resolvers
