### ISSUE TITLE
[nvim-0.9] discrepancies in filepath normalization

### ISSUE THREAD

**Issue by A-Lamia** [cbochs/grapple.nvim#47]
Hey was just doing some testing and thought i would let you know about these if you didn't already. :D

1. tags from version 0.8 don't carry over to 0.9
2. the title and the tag value on the popup menu are full file / folder paths instead of being relative.

**Comment by A-Lamia** [comment]
With the first issue it seems to be something difference with how scope is happening from v0.8 to v0.9

**Comment by cbochs** [comment]
Interesting. Thanks for letting me know! 

I think this does have to do with the differences between plenary and nvim-0.9. Plenary will try to use `/` or `\` base on the os, but it might be that nvim-0.9 uses [`vim.fs.normalize`](https://neovim.io/doc/user/lua.html#vim.fs.normalize()). When I get the chance, it might be good to explore moving entirely from plenary to `vim.fs`

**Comment by cbochs** [comment]
I haven't created a migration for this yet, but working on introducing a `path` module to try to decouple from plenary and guarantee some consistency (prefer forward-slashes `/`) between scopes and tagged file paths. See #54

**Comment by A-Lamia** [comment]
Oh that's good the unreadable names have been a little annoying 😅

**Comment by A-Lamia** [comment]
oh never saw https://github.com/cbochs/grapple.nvim/pull/54, this fixes the inconstancy with forward and backslashes only one issues now.

User is the working Directory pop up title looks like below:
`C:/Users/Lamia/AppData/Local/nvim/lua/user` 
should be 
`user`

and the files are displaying the full path as well eg:
`[1]C:/Users/Lamia/AppData/nvim/lua/user/init.lua`
should be:
`user/init.lua`
or
`init.lua` 

can't actually remember what the original was been using the messed up version for so long.

I think something cool could be showing only the file name and if 2 files have the same name show 1 folder back eg:

`[1] user/init.lua`
`[2] plugins/init.lua`
`[3] grapple.lua`

thanks for the effort! :D

**Comment by A-Lamia** [comment]
Hmm after further use no it seems https://github.com/cbochs/grapple.nvim/pull/54 is broke,

1. Grapple files are not being saved out.
2. When Grapple goes to write out it clears any local grapple data.
3. Re-ordering grapple files does not work when toggling tags.

**Comment by cbochs** [comment]
> oh never saw https://github.com/cbochs/grapple.nvim/pull/54, this fixes the Inconsistency with forward and backslashes only one issues now.

> Hmm after further use no it seems https://github.com/cbochs/grapple.nvim/pull/54 is broke,

Ah, yeah... This was a WIP refactor that I let slide. It should really be marked as a "draft". I will try to get back to finishing it soon, just haven't had much time recently.

> "User" is the working directory pop up title looks like below:
> `C:/Users/Lamia/AppData/Local/nvim/lua/user`
> should be:
> `user`

To clarify, is `C:/Users` the working directory or is `C:/Users/Lamia/AppData/Local/nvim/lua/user` the working directory? There could be a bit of confusion on Grapple's side when there are similarities between the parent and child directories.

> I think something cool could be showing only the file name and if 2 files have the same name show 1 folder back eg:
> `[1] user/init.lua`
> `[2] plugins/init.lua`
> `[3] grapple.lua`

I also like the idea of a "smart" file path. It has been on my radar to add, there's just a bit of complexity in this approach when trying to determine what the user has changed in the buffer. Some takes on this "modifiable buffer" can be found in [elihunter173/dirbuf.nvim](https://github.com/elihunter173/dirbuf.nvim) using an index prefix, but I would like to keep the popup as unobtrusive as possible. The feature does seem doable though, would just need some research 🙂

**Comment by A-Lamia** [comment]
All good man take your time, It's still usable as is, just a little messy 😉

>To clarify, is C:/Users the working directory or is C:/Users/Lamia/AppData/Local/nvim/lua/user the working directory? 

as for the correct path the `user` at the end not `C:/User` so it is showing the full path to that `/lua/"user"` folder .

>The feature does seem doable though, would just need some research 🙂

What ever works best man hahaha, not an important feature anyway it's good to know it's on the back burner though.

**Comment by cbochs** [comment]
Going to close this. Working on a [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite) which will remove plenary.nvim, standardize paths, and also allow for some form of "smart paths". Stay tunes 🙂
