### ISSUE TITLE
[Question] How to get Cmdline popup shown in README git?

### ISSUE THREAD

**Issue by ejuarezg** [cbochs/grapple.nvim#55]
Not really an issue, but I was curious how you got the Cmdline popup that is shown in the example gif in the README?

I apologize if this is not the right place to ask such a question.

**Comment by cbochs** [comment]
All good!

The showcase is using Noice.nvim (https://github.com/folke/noice.nvim) for the cmdline prompt.

**Comment by ejuarezg** [comment]
Thank you!
