### ISSUE TITLE
Sorry if this should be clear, but what happened to GrappleJumpBackward

### ISSUE THREAD

**Issue by leath-dub** [cbochs/grapple.nvim#56]
Unless I am mistaken, there used to be a command, `GrappleJumpBackward`, which would bring you to the previous tag( allowing you to swap between 2 tags ). Just asking what happened or what the options are to emulate the same behaviour, thanks in advance :)

**Comment by cbochs** [comment]
This has been removed and replaced in favour of the [`GrappleCycle`](https://github.com/cbochs/grapple.nvim#grapplecycle) command. To move forward / backward you can use `GrappleCycle forward` or `GrappleCycle backward`. With the Grapple API, you would use:

```lua
# :GrappleCycle forward
require("grapple").cycle_forward()

# :GrappleCycle backward
require("grapple").cycle_backward()
```

**Comment by leath-dub** [comment]
I know of these however I thought there was a function that kept track of the previous(as in last visited)

**Comment by cbochs** [comment]
@leath-dub did the above answer your question? Can I close this issue?

**Comment by leath-dub** [comment]
sorry yeah it did , :)

**Comment by cbochs** [comment]
Awesome 🙂
