### ISSUE TITLE
Getting this error "Expected the end but found T_ARR_END at character 137"

### ISSUE THREAD

**Issue by kamalarieff** [cbochs/grapple.nvim#57]
Hi @cbochs. Firstly I would like to express my gratitude for this plugin. It's very useful for me.

However, I'm encountering this issue after I updated my plugins on 20 Jan 2023.

Error logs:

```
Error detected while processing /home/kamalarieff/.vim/plugged/grapple.nvim/plugin/grapple.vim:                                                                          
line    1:                                                                                                                                                               
E5108: Error executing lua .../migrations/20221130_separate_named_and_indexed_tags.lua:18: Expected the end but found T_ARR_END at character 137                         
stack traceback:                                                                                                                                                         
        [C]: in function 'decode'                                                                                                                                        
        .../migrations/20221130_separate_named_and_indexed_tags.lua:18: in function 'migrate'                                                                            
        ...eff/.vim/plugged/grapple.nvim/lua/grapple/migrations.lua:31: in function 'migrate'                                                                            
        /home/kamalarieff/.vim/plugged/grapple.nvim/lua/grapple.lua:23: in function 'initialize'                                                                         
        [string ":lua"]:1: in main chunk 
```

I'm using Vim Plugged and encountering this issue with `Plug 'cbochs/grapple.nvim'` alone without running `require('grapple').setup()`.

I've tried uninstall and reinstalling by removing `grapple.nvim` folder from `~/.vim/plugged` but no luck.

Any idea how to fix it?

If you need more information, I'm happy to provide them for you.

**Comment by cbochs** [comment]
It appears that one of the save files in `~/.local/share/nvim/grapple` is malformed and cannot be json decoded. Specifically, if fails on character 137.

Do any of the files in `~/.local/share/nvim/grapple` appear to be invalid JSON? Maybe possibly contain unicode characters?

One solution would be to delete the erroneous file and let the migration continue, but I'd be interested to know what the cause of this error is.

**Comment by kamalarieff** [comment]
It works after I deleted them. I forgot to check the contents of the file though :sweat_smile: .

Thanks a lot @cbochs. Consider this issue solved.
