### ISSUE TITLE
[Question/Request] Multiple tags per file

### ISSUE THREAD

**Issue by lawrence-laz** [cbochs/grapple.nvim#58]
This seems like a very nice plugin!

The only thing I am missing is being able to add multiple tags in a single file/buffer and cycle through them. 

Is this something that is currently possible or would be considered as a possible feature?

Thanks

**Comment by cbochs** [comment]
Grapple only allows one tag per file. This is because your cursor location is tracked on a per-file basis. If you'd like to mark specific locations within a file, I'd recommend using `:h mark`.

**Comment by lawrence-laz** [comment]
Got it, thanks!
