### ISSUE TITLE
How do I create a global tag while keeping project scope ? 

### ISSUE THREAD

**Issue by blob42** [cbochs/grapple.nvim#59]
Hi, thanks for this great plugin. 

I read through the documentation and I couldn't find anywhere this simple use case. 

I setup my config with the `git` scope resolver so my named tags are by default per project. However I also would like to create global scoped tags. How do I do so ? the documentation only covers how to create new scopes ? 

Am I supposed to call again grapple with the `global` scope option ? That would mean If I want a shortcut to create a global scope my lua func needs to call the setup with `global` scope register the tag then call again setup with `git` scope ?

**Comment by cbochs** [comment]
Definitely an oversight. The plan was to add this once I stabilized the Scope API, but never got around to adding it 🙂

**Comment by blob42** [comment]
Thanks for the update if I knew it would be so fast I would not have created wrapper functions everywhere 😭
