### ISSUE TITLE
FR: Option to change the location where the persistent data is saved

### ISSUE THREAD

**Issue by chrisgrieser** [cbochs/grapple.nvim#61]
Right now, the data is saved in `fn.stdpath("data")`. However, when working on multiple devices, I'd ideally like to sync the grapple's tags along with my other dotfiles. 

Changing nvim's data directory to a location in my dotfile repo is not a suitable solution, package managers like lazy or mason all save the plugins/packages there as well.

**Comment by cbochs** [comment]
You [technically can](https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/settings.lua#L16-L18), but I had left it undocumented 🙂

You can change it with:

```
require("grapple").setup({
  save_path = {save_path}
})
```

**Comment by chrisgrieser** [comment]
thanks!

**Comment by cbochs** [comment]
As requested: aab04507944da7f6b4b1cab6d2ca1585ad580a27 :)
