### ISSUE TITLE
Question/Bug: how to update the current scope?

### ISSUE THREAD

**Issue by chrisgrieser** [cbochs/grapple.nvim#62]
First of all, thanks you for this plugin – was looking for something like Harpoon, but with a bit more flexibility.

So regarding this issue, I am not sure whether this is a bug or whether I simply have not figured out how the caching of this plugin works. For whatever reason, I can't get the scope to update when changing file / working directory, it seems I am always stuck with the first scope after nvim-startup.

Now my directory structure looks like this. I have `~/.config` set up as my dotfile repo, and it contains various config folders. With `.root(".luarc.json")`, I'd like to have `hammerspoon` and `nvim` to be treated as different project scopes. 

```txt
.
├── .git
├── (...other config directories)
├── hammerspoon
│   ├── init.lua
│   ├── .luarc.json
│   └── lua
│       ├── file_A.lua
│       └── ....lua
└── nvim
    ├── init.lua
    ├── .luarc.json
    └── lua
        ├── config
        │   ├── file_B.lua
        │   └── ....lua
        └── ....lua

```
---

Here is my config using lazy
```lua
{
	"cbochs/grapple.nvim",
	dependencies = "nvim-lua/plenary.nvim",
	init = function()
		local my_resolver = require("grapple.scope").fallback({
			require("grapple.scope").root(".luarc.json"),
			require("grapple").resolvers.git_fallback,
			require("grapple").resolvers.directory,
		})
		require("grapple").setup {
			scope = my_resolver,
		}
	end,
},
```

Now, since both hammerspoon and nvim are lua configs, I frequently switch from one to the other to copy some lua code. However, I cannot get grapple.nvim to behave as I would expect. So here is what I did:
1. Open nvim at `file_A.lua`. `require("grapple").popup_scopes()` correctly lists `~/.config/nvim` as scope. 
2. I tag `file_A.lua`, running `popup_scopes()` shows that for the `~/.config/nvim`, the number of tagged files correctly incremented from 0 to 1.
3. I switch to `file_B.lua` via Telescope. Since the hammerspoon directory has it's own `.luarc.json`, I am expecting it is treated as an independent scope.
4. I open up `popup_scopes()`, and it's still showing `~/.config/nvim` as the only scope. 
5. I tag the current file ( `file_B.lua`) and when I check `popup_scopes()` once more, it shows that only the scope `~/.config/nvim`, now updated to 2.
6. I quit nvim. I open nvim at `file_B.lua`. Now it correctly shows `~/.config/hammerspoon` as scope, but there are 0 tagged files. 
7. Switching to `file_A.lua` via Telescope does not result in an updated scope.
8. I quit nvim and open it again at `file_A.lua`. The scope shown is now `~/.config/nvim`, with the number 2.

---

So reading through the docs, I tried two things:
A. changing the `cache` option for the resolver, to force it to always update.
```lua
my_resolver = require("grapple.scope").fallback({
	require("grapple.scope").root(".luarc.json"),
	require("grapple").resolvers.git_fallback,
	require("grapple").resolvers.directory,
}, { cache = false })
```
However, this did not change the behavior described above.

B. I tried adding an auto-command that updates the resolver on buffer enter:
```lua
vim.api.nvim_create_autocmd("BufEnter", {
	pattern = "*",
	callback = function()
		require("grapple.scope").update(my_resolver)
	end,
})
```

This, too, did not not change the behavior described in steps 1-8. Probably, I am just missing something obvious about how/when the resolver updates, but even after trying for 3 hours, I just can't figure it out :(

**Comment by cbochs** [comment]
Hey @chrisgrieser, I think the scope resolver you've defined is correct. However, I would note that the `root`, `git_fallback`, and `directory` scope resolvers use the `"DirChanged"` autocmd to invalidate their cache. When you use telescope to open `file_B.lua`, is your current directory being changed to `~/.config/hammerspoon` (check with `:pwd`)? I might suggest looking into [`:h 'autochdir'`](https://neovim.io/doc/user/options.html#'autochdir').

As an alternative you could define a custom scope that resolves a "root" directory from a file path's directory name:

```lua
local dotfile_resolver = require("grapple.scope").resolver(function()
  local file_path = vim.api.nvim_buf_get_name(0)
  local base_dir = vim.fs.dirname(file_path)
  local root_files = vim.fs.find({ ".luarc.json" }, { path = base_dir, upward = true })
  if #root_files > 0 then
    return vim.fs.dirname(root_files[1])
  end
  return nil
end, { cache = "BufEnter" })
```

Use it like:

```lua
local resolver = require("grapple.scope").fallback({
	dotfile_resolver,
	require("grapple").resolvers.git_fallback,
	require("grapple").resolvers.directory,
})
```

**Comment by chrisgrieser** [comment]
Thanks a lot for the answer! the `pwd` does indeed change, but it still did not work 🤔 

Nevertheless, you second suggestions seems to work, thanks!

**Comment by cbochs** [comment]
> Thanks a lot for the answer! the `pwd` does indeed change, but it still did not work 🤔

Interesting. I wasn't able to reproduce this issue. I'll keep an eye open to see if it crops up again.

> Nevertheless, you second suggestions seems to work, thanks!

Happy to help 🙂 In fact, this might be a useful default resolver to provide. I'll see about adding it to the builtin resolvers.

**Comment by cbochs** [comment]
@chrisgrieser a quick update: I'm working on adding the above scope resolver to Grapple. If you'd like to try it out, feel free to checkout the `feat_scope_root_from_buffer` branch (PR: #63). To use it:

```lua
require("grapple.scope").root_from_buffer(".luarc.json")
```
