### ISSUE TITLE
[Feature request] Support sign column (signs)

### ISSUE THREAD

**Issue by akinsho** [cbochs/grapple.nvim#65]
Hi again,

As part of trying out portal I've also dug into `grapple` and really like this as an alternative to something like native marks which I've lost faith will every really serve my purposes which is really just a per project bookmarking system (which I don't think is what they were intended for anyway).

This plugin looks like a really good fit for that although one thing I think would be super useful would be to have some sort of sign in the signcolumn so I can remember/see at a glance where/if there are bookmarks in a file similar to

 ![image](https://camo.githubusercontent.com/916a9d2729c9ecaea5412df20e77d6e2eb9b3d697ead106a65235ac0efb7a472/68747470733a2f2f7261772e6769746875622e636f6d2f4d617474657347726f656765722f76696d2d626f6f6b6d61726b732f6d61737465722f707265766965772e676966)
from https://github.com/MattesGroeger/vim-bookmarks or https://github.com/chentoast/marks.nvim

I appreciate there's a popup menu but I'm thinking something much more minimal than that so you can just see at a glance where the bookmarks are and say you'd forgotten there was one in the file or you added it to the wrong line or wanted to change it you have this easy visual indicator

**Comment by cbochs** [comment]
When a file is tagged, its "mark" is essentially the tracked cursor location. This means that - unlike native marks or marks.nvim - an indicator in the sign column would be always moving and essentially just be following the cursor.

An alternative, however, is to add a small section to your statusline that indicates whether the current buffer is tagged or not: https://github.com/cbochs/grapple.nvim#statusline

Looks a little something like this:

<img width="196" alt="image" src="https://user-images.githubusercontent.com/2467016/223152726-8506c352-f429-4f99-b7bb-9b000ee5d094.png">

Does this help?

**Comment by akinsho** [comment]
@cbochs so the mark is kind of a track of the last place you were in a file, so you can't tag like a specific function in a gigantic file and come back to that precise spot? (sorry I should have had a closer look at this behaviour before opening this issue)

**Comment by cbochs** [comment]
No problem. Yes, the mark just tracks the last known location of your cursor so that you can easily hop directly to that location. It doesn't let you choose a static location.

Although, I'm curious. What is the workflow you imagined / perceived that was different from native marks?

**Comment by akinsho** [comment]
@cbochs the main value of this plugin (for me) over marks would be to
1. save marks per project/dir/branch etc. I'd settle for any of those really given that native lowercase marks are buffer local or global uppercase marks are across every file ever which means you only really have 26 which isn't particularly useful for me.
2. To have these persisted in a way that works, there's currently an issue with marks in nvim where they essentially never get removed from shada so they always resurrect when you reload the file in nvim. There's a WIP PR for that but this is solved here which is useful.

Regarding the workflow I had in mind I thought this would give me the 2 above features as well as the static marking functionality. It's not a deal breaker since I think sometimes I do just want to go back to where I was in a file but some other times I'm working on a feature and only a particular part of the file is relevant to me so I always want to be brought back there, if the file is particularly large or the codebase sufficiently big and I've gone off piste then going back to the file at my last location can sometimes just be very confusing since I don't even recognise the file. I had imagined that this plugin would just have static marks similar to native marks 🤷🏿

**Comment by cbochs** [comment]
> 1. save marks per project/dir/branch etc. I'd settle for any of those really given that native lowercase marks are buffer local or global uppercase marks are across every file ever which means you only really have 26 which isn't particularly useful for me.

This is a good point and use case. How often would you say you have >1 mark on a single file? Would something along the lines of "freezing" a file tag be useful?

> 2\. To have these persisted in a way that works, there's currently an issue with marks in nvim where they essentially never get removed from shada so they always resurrect when you reload the file in nvim. There's a WIP PR for that but this is solved here which is useful.

Do you have the link to this PR?

> if the file is particularly large or the codebase sufficiently big and I've gone off piste then going back to the file at my last location can sometimes just be very confusing since I don't even recognise the file.

This is certainly a hard balance to strike. I had this problem as well and the combination of Grapple.nvim and Portal.nvim have greatly helped my workflow. However, it sounds like there is room for improvement integrating static (native) marks/bookmarks with Grapple's scope resolution.

Thanks for the feedback 🙂

**Comment by akinsho** [comment]
The PR is https://github.com/neovim/neovim/pull/16067 for the mark removal shada issue.

Freezing the tag could help maybe there's an option to have live or "frozen" tags either per call to `mark|toggle` etc. or in the config i.e. I prefer generally to have `live|frozen`. 

Tbh I haven't really tried with live marks to see whether that is actually not that big a deal for me. Was more just a bit of surprise that the value of the mark changes after I mark it.

**Comment by cbochs** [comment]
> The PR is [neovim/neovim#16067](https://github.com/neovim/neovim/pull/16067) for the mark removal shada issue.

Thanks for the link!

> Freezing the tag could help maybe there's an option to have live or "frozen" tags either per call to `mark|toggle` etc. or in the config i.e. I prefer generally to have `live|frozen`.

Ah, gotcha. Have heard of or tried [LeonHeidelbach/trailblazer.nvim](https://github.com/LeonHeidelbach/trailblazer.nvim)? It might be _closer_ to what you're looking for?

Alternatively, if you're feeling adventurous, you can use Grapple's scope resolution and state management to save just about any json serializable data: https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/state.lua#L181-L188 😉

**Comment by akinsho** [comment]
Hadn't heard of `Trailblazer.nvim` the README is huge will have to give it a careful read through and see if it would work thanks, although tbh I don't really like hopping plugins anyway I'll see how I get on adapting to grapple as is before investigating other mechanisms.

**Comment by cbochs** [comment]
I hope you enjoy using Portal.nvim and Grapple.nvim! I will keep static tags on my radar and investigate to how I can integrate them nicely into Grapple. If you find any other issues or have more suggestions, please let me know!

Re: I'll close this issue and use a new tracking issue (#66) I've created for evaluating having multiple tags per file.
