### ISSUE TITLE
Tag only filepath

### ISSUE THREAD

**Issue by ShinyZero0** [cbochs/grapple.nvim#68]
There are plugins to save the cursor position for each file e.g. (n)vim-lastplace, but when i open the file with Grapple it overwrites the cursor position with the one where it was when file was tagged. Is there a way to prevent that and restore the latest cursor position?

**Comment by ShinyZero0** [comment]
With this minimal config:
```lua
require("lazy").setup(
{
  {
    "ethanholz/nvim-lastplace",
    config = true,
  },
  {
    "cbochs/grapple.nvim",
    config = function()
      require("grapple").setup()
      vim.keymap.set("n", "<leader>M", require("grapple").toggle)
      vim.keymap.set("n", '<leader>"', require("grapple").popup_tags)
    end,
      dependencies = {
        "nvim-lua/plenary.nvim",
      },
    }
  }, {})
```
I need to make some changes and write the file to save the cursor position for opening later with Grapple, otherwise it'll load the last saved (when the file was tagged or written) position, while if i just open the file with Netrw i'll get the true last position (thanks to lastplace) without writing the file before that. Is it necessary to provide a bunch of screenshots?

**Comment by ShinyZero0** [comment]
Played around with that a bit, Grapple doesn't save the cursor poition even on writing the file if i exit vim with <C-q> mapped to <cmd>q<CR> or :q<CR>, i tried both. When i manually enter :q to cmdline, it works well

**Comment by ShinyZero0** [comment]
Seems like if i trigger the `CmdLineEnter` event with `:` or `;` remapped to `:`, press `<ESC>`
 and then quit with `<C-q>` it also saves the cursor position. Is Grapple's cursor saving function listening to this event? Maybe make it listen to `BufLeave` or something

**Comment by ShinyZero0** [comment]
There is the same problem with Harpoon, and with minimal config i sent there it is not saved even with :q command not in Grapple nor in Harpoon, but with both it is saved at least by :q in my config

**Comment by cbochs** [comment]
@ShinyZero0 thanks for digging into this. I'm working a bit right now on fixing up how grapple handles syncing tags, which should solve the few issues you pointed out above.

As for the (n)vim-lastplace cursor placement, grapple is expected to behave very similar to (and if not the same as) them when setting the cursor location. The fact that is does not should be considered a bug, which I'll look at addressing when I get the chance.

Thanks for feedback!
