### ISSUE TITLE
Quick select?

### ISSUE THREAD

**Issue by textzenith** [cbochs/grapple.nvim#70]
Hi, and thanks for developing this plugin, which I'm using because it seems a lot more thoughtful in its base design compared to e.g. Harpoon!

I think that what I expected... What I expected was a super-speedy "quick switch". In my "Vim Workshop" project, for example, I have the following files tagged:

```
[p] plugins.lua
[v] init.vim
[l] init.lua
[t] todo
```
I'd like to open a popup and immediately hit p, for example, to go to plugins.lua.

Now I really do like the normal-mode functionality you get from entering `GrapplePopup tags`, it's really nice to edit your tagged files like in an ordinary text document. So perhaps this could be a third modality, `GrapplePopup quick`.

This raises the question of how to iteratively select when you have many tags with tag length > 1. The interface could be similar to fzf or Telescope. Which in turn raises the question: How about Telescope integration?

Anyway, that's just something else to think about! Have you thought about adding this? (I might even pop you a PR when I have time for Vim hacking later next week). What other ideas have you imagined for future versions of Grapple? :smiley:

**Comment by adaviloper** [comment]
I'd also be interested in this feature!

**Comment by cbochs** [comment]
Great suggestion. Apologies, I haven't had time to work on this project for a while. 

I've been working on a [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite) that allows some more flexibility for operations like this. Right now it supports quick-selection from 1..9. Would that be sufficient? For example,

<img width="496" alt="image" src="https://github.com/cbochs/grapple.nvim/assets/2467016/b26dd226-af71-4cff-85ae-f201290349a2">

Feel free to try out the branch `rewrite`, if you're interested! There are more goodies than just quick selection 🙂 **Please note**, there are breaking changes in the file format so your previous tags won't be loaded (not deleted, however). Also, the user command has been updated:

```
GrappleTag -> Grapple tag
GrappleUntag -> Grapple untag
GrappleToggle -> Grapple toggle
GrapplePopup tags -> Grapple open_tags
```
