### ISSUE TITLE
Unstable order of named tags

### ISSUE THREAD

**Issue by andrhua** [cbochs/grapple.nvim#71]
I have two related problems:
1. order of named tags upon loading into a scope seems random. To reproduce, open nvim, load into git directory, and call `popup_tags("git")`, then close nvim and repeat. I observed following orderings for 4 named tags: `abcd, adbc, cadb`
2. It's not really clear from help page how to reorder named tags and save it. I tried pressing enter, closing window with `q`, `esc`, `:q`, `:w` spits the `E382: Cannot write, 'buftype' option is set` error. The order stays as before making any changes. The only reliable way to change it is to reopen nvim :smiley:  Perhaps is has to do something with caching?

**Comment by cbochs** [comment]
@andrhua Thanks for raising this issue. Apologies, I haven't had time to work on this project for a while.

Unfortunately, the order for named tags is not guaranteed. Serializing and deserializing json does not guarantee that the lua table will be reconstructed deterministically. This means that reordering them will likely not be saved.

Recently, I have been working on a [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite). It doesn't support named tags yet, but I think that this is something that could be fixed going forward.

Feel free to try out the branch `rewrite`, if you're interested! It has a few UI goodies 🙂 **Please note**, there are breaking changes in the file format so your previous tags won't be loaded (not deleted, however). Also, the user command has been updated:

```
GrappleTag -> Grapple tag
GrappleUntag -> Grapple untag
GrappleToggle -> Grapple toggle
GrapplePopup tags -> Grapple open_tags
```

**Comment by cbochs** [comment]
@andrhua A quick update, the rewrite now supports named tags and they can be moved around just like all other tags
