### ISSUE TITLE
Feature Request: Emit autocmd event on tag updates

### ISSUE THREAD

**Issue by Subjective** [cbochs/grapple.nvim#73]
Hi, thanks for the great plugin! As others have already mentioned, I've been enjoying using grapple for file navigation as it seems quite polished for purpose, compared to its counterpart harpoon which has a lot of extras I don't use. 

While I'm mostly satisfied with the experience, I was wondering if it would it be possible to emit an autocmd event every time tags are added/deleted/toggled/reset? It would be really helpful for integrating grapple into a statusline plugin like heirline, which updates based on events rather than a time interval.

Thanks again, and have a nice day :)

**Comment by cbochs** [comment]
@Subjective Thanks for the suggestion and all the PRs! Apologies, I haven't had time to work on this project for a while. 

I've been working on a [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite). It will include an event like this. For now, I'm happy to merge your PR. However, I would suggest using the name `GrappleUpdate`.

Also, feel free to try out the branch `rewrite`, if you're interested! 🙂 **Please note**, there are breaking changes in the file format so your previous tags won't be loaded (not deleted, however). Also, the user command has been updated:

```
GrappleTag -> Grapple tag
GrappleUntag -> Grapple untag
GrappleToggle -> Grapple toggle
GrapplePopup tags -> Grapple open_tags
```
