### ISSUE TITLE
how to toggle popup menu?

### ISSUE THREAD

**Issue by 7c78** [cbochs/grapple.nvim#86]
Hi, I would like to be able to open the tag menu (I am using `grapple.popup_tags`) and close the menu using the same keystroke. How can I achieve that?

Thanks

**Comment by cbochs** [comment]
Would something like this work?

```lua
vim.keymap.set("n", "{keymap}", "<cmd>GrapplePopup tags<cr>")

vim.api.nvim_create_augroup("Toggle", { clear = true })
vim.api.nvim_create_autocmd("FileType", {
    group = "Toggle",
    callback = function(opts)
        vim.keymap.set("n", "{keymap}", "<cmd>close<cr>", { buffer = opts.buf })
    end,
})


```

**Comment by cbochs** [comment]
I'm going to close this. If you need any further assistance, please feel free to open it again. Thanks!

**Comment by 7c78** [comment]
It works. Thank you very much.

**Comment by cbochs** [comment]
@7c78 the above is not the correct answer anymore. I've made some changes and it is just a simple command now (see [Tags Window](https://github.com/cbochs/grapple.nvim?tab=readme-ov-file#tags-window)):

```lua
-- Command
vim.keymap.set("n", "{keymap}", "<cmd>Grapple toggle_tags<cr>")

-- Lua API
vim.keymap.set("n", "{keymap}", require("grapple").toggle_tags)
```

**Comment by 7c78** [comment]
@cbochs Oh nice. Thank you very much.
