### ISSUE TITLE
Grapple tag an oil directory window

### ISSUE THREAD

**Issue by dbatten5** [cbochs/grapple.nvim#88]
Great plugin, many thanks for developing it.
Sometimes I want to tag a directory rather than a file. I'm using `oil.nvim` as a directory explorer and I've tried tagging an `oil` window (which has a filepath something like `oil:///path/to/directory/`. The tag is viewable in the `GrapplePopup tags` window but then if I open another file the tag disappears from the popup.

**Comment by cbochs** [comment]
@dbatten5 Great suggestion. I've been using oil.nvim myself recently and its a very useful plugin.

Support will likely not be available for this right now. However, the [rewrite](https://github.com/cbochs/grapple.nvim/tree/rewrite) I'm working on should address more general URIs (i.e. `ssh`, `scp`, or `oil`).

Feel free to try out the branch `rewrite`, if you're interested though! **Please note**, there are breaking changes in the file format so your previous tags won't be loaded (not deleted, however). Also, the user command has been updated:

```
GrappleTag -> Grapple tag
GrappleUntag -> Grapple untag
GrappleToggle -> Grapple toggle
GrapplePopup tags -> Grapple open_tags
```

**Comment by dbatten5** [comment]
Awesome, looking forward to the rewrite

**Comment by dbatten5** [comment]
Awesome, looking forward to the rewrite
