### ISSUE TITLE
feat(scope): git commit scope resolution

### ISSUE THREAD

**Issue by cbochs** [cbochs/grapple.nvim#9]
For those working with git work-tree, it should be possible to make tags more granular when performing scope resolution. Specifically, git commits should be suffixed to the scope to further specify a tag scope.

### Add `git` scope resolution

* Expose `resolve_scope` as a module function
* Add `resolve_scope_in_parts` function to return both `file_path` and git `commit` of a scope
* Refactor `resolve_scope` function to use `resolve_scope_in_parts`
* Add `git` configuration option

### Update README with relevant details

* Update configuration section
* Update `Tag Scopes` section

**Comment by A-Lamia** [comment]
It would be nice if the scope would resolve as such `.git > lsp > directory`, not sure if you have already though of this :)

**Comment by cbochs** [comment]
Interesting idea! This should be possible (albeit not built-in) by passing in a function to `scope` as part of the setup with something like:

```lua
require("grapple").setup({
    scope = function()
        -- Attempt to use a git directory as the project scope
        local root_files = vim.fs.find(".git", { upward = true })
        if #root_files > 0 then
            return vim.fs.dirname(root_files[1])
        end

        -- Fallback to "lsp", which will fallback to "directory" if not found
        return require("grapple.scope").resolve("lsp")
    end
})
```

**Comment by A-Lamia** [comment]
Awesome, though looks like something isn't running.
![image](https://user-images.githubusercontent.com/6450181/202834833-fb1529b0-c821-4ca4-b649-454c4ab3db1c.png)

**Comment by cbochs** [comment]
Hm. How did you hit this error? It looks like might have been running `:GrappleTag`? Was there a specific set of arguments you used to hit this error?

**Comment by A-Lamia** [comment]
@cbochs nope just used ":GrappleTag", am i doing something wrong?
Thought it was supposed to by default tag the current buffer.

**Comment by cbochs** [comment]
That's correct. Does this happen when you call `:GrappleTag` for any file? If possible, what is the output of `:lua =vim.api.nvim_buf_get_name(0)` when you have that buffer open?

**Comment by A-Lamia** [comment]
@cbochs seems to return back the path of the current buffer `X:\\Projects\CPP\ShaderVis\main.cpp`

**Comment by A-Lamia** [comment]
GrapplePopup:
![image](https://user-images.githubusercontent.com/6450181/202836303-f876aae7-4817-4176-a2a6-19f15fcc17e9.png)

GrappleToggle:
![image](https://user-images.githubusercontent.com/6450181/202836314-c1173143-58b3-4601-bbd7-d8d40e048c89.png)

**Comment by cbochs** [comment]
That's kind of what I thought this would be. Paths have only been naively implemented in grapple.nvim, always assuming unix-style (`/`). This assumption breaks down for Windows. I've created https://github.com/cbochs/grapple.nvim/issues/31 to follow-up with this. Sorry for the inconvenience!

**Comment by A-Lamia** [comment]
Haha all good, guess ill be waiting for the update ;D

**Comment by cbochs** [comment]
Back on-topic with this issue:

Idea: to support finer grained scopes like git branches, commits, or other VCS systems, use the concept of a `ScopeSuffix` where a scope can now appear as one of the following:

* Without suffix: `{scope_path}`
* With suffix: `{scope_path}#{suffix}`

Advantages:
* Easily parsed into a `scope_path` and `suffix`
* Extendible, supports adding a config option like `config.suffix` for customizing the type of suffix used.

**Comment by A-Lamia** [comment]
I like it, basically being able to chain your fall backs.

**Comment by cbochs** [comment]
This is slightly different than fallback chaining. More along the lines of supplementing a project scope so users can have tags that are associated with something like specific git branch (i.e. `/my/git/project#main` and `/mygit/project#dev`).

For now, fallback chaining should probably be left to a custom function. However, I think some API should be provided to more easily what the project (root) directory is. Maybe along the lines of 6e3cd09ccd27088fc2f6e5b3edabcf909c2ae5ae

**Comment by cbochs** [comment]
This has been implemented as `git_branch` using an async scope resolver (see: https://github.com/cbochs/grapple.nvim#project-scopes).
