### ISSUE TITLE
How to set a scope based on the current working directory and git branch

### ISSUE THREAD

**Issue by adaviloper** [cbochs/grapple.nvim#91]
Before this latest update, I was able to achieve a custom scope by using the following setting:

```
scope = 'git_branch',
  scope = require('grapple.scope').suffix(
    require('grapple').resolvers.directory,
    require('grapple').resolvers.git_branch_suffix,
    {
      persist = true,
    }
),
```
This would be used to restrict the scopes to child directories in a project that are also restricted to a branch based on the git repository of the parent.

```
// git repo
~/Projects/foo

// frontend sub-project
~/Projects/foo/frontend

// admin sub-project
~/Projects/foo/admin
```
Given the above project structure, ideally I would want to open up a separate neovim instance in each of those and the scope above would generate three discrete scopes:
```
.../foo#<my-feature-branch>
.../foo/frontend#<my-feature-branch>
.../foo/admin#<my-feature-branch>
```

The goal for something like this would be able to maintain separate scopes within a single repository based on the sub-folder that I'm working in.

How would I be able to achieve something similar to the scope I was using under the new API changes?

**Comment by cbochs** [comment]
Hey @adaviloper! Thanks for following up with this question here.

A couple good starting points:
- The README: https://github.com/cbochs/grapple.nvim?tab=readme-ov-file#grapplescope_definition
- The definition of `git_branch`: https://github.com/cbochs/grapple.nvim/blob/main/lua/grapple/settings.lua#L84-L110

In your case, you may be able to (almost verbatim) use `git_branch` by simply swapping the path used for `root`. Maybe try something like this in your `settings.scope`?

```lua
{
    name = "cwd_branch",
    desc = "Current working directory and git branch",
    fallback = "cwd",
    cache = {
        event = { "BufEnter", "FocusGained" },
        debounce = 1000, -- ms
    },
    resolver = function()
        local git_files = vim.fs.find(".git", { upward = true, stop = vim.loop.os_homedir() })
        if #git_files == 0 then
            return
        end

        local root = vim.loop.cwd()

        local result = vim.fn.system({ "git", "symbolic-ref", "--short", "HEAD" })
        local branch = vim.trim(string.gsub(result, "\n", ""))

        local id = string.format("%s:%s", root, branch)
        local path = root

        return id, path
    end,
},

```

**Comment by adaviloper** [comment]
@cbochs This seems to work perfectly! Thanks so much for helping with this!
