### ISSUE TITLE
Suggestion: use toggle UI instead of open_*

### ISSUE THREAD

**Issue by vunhatchuong** [cbochs/grapple.nvim#94]
It feels unintuitive to use a shortcut to open it and press `ESC` to close it. And there's no way to check the state of the UI, so I can't write my own func.

**Comment by cbochs** [comment]
Great suggestion!

**Comment by cbochs** [comment]
> And there's no way to check the state of the UI, so I can't write my own func.

Also note, you _can_ hook into any Grapple window by it's filetype (`grapple`)
