### ISSUE TITLE
nvim-web-devicons dependency not mentioned

### ISSUE THREAD

**Issue by niveK77pur** [cbochs/grapple.nvim#98]
Hello! I have been playing around with this plugin a little, and it is wonderful! I will very likely be incorporating this into my workflow!

When calling the `toggle_tags` (or `open_tags` for that matter) method, it returns this error:

```
E5108: Error executing lua: ...share/nvim/lazy/grapple.nvim/lua/grapple/tag_content.lua:102: The plugin "nvim-tree/nvim-web-devicons" is required
stack traceback:
        [C]: in function 'error'
        ...share/nvim/lazy/grapple.nvim/lua/grapple/tag_content.lua:102: in function 'get_icon'
        ...share/nvim/lazy/grapple.nvim/lua/grapple/tag_content.lua:147: in function 'create_entry'
        ...ocal/share/nvim/lazy/grapple.nvim/lua/grapple/window.lua:349: in function 'render'
        ...vinb/.local/share/nvim/lazy/grapple.nvim/lua/grapple.lua:417: in function 'open'
        ...vinb/.local/share/nvim/lazy/grapple.nvim/lua/grapple.lua:467: in function 'open_fn'
        ...vinb/.local/share/nvim/lazy/grapple.nvim/lua/grapple.lua:431: in function 'toggle'
        ...vinb/.local/share/nvim/lazy/grapple.nvim/lua/grapple.lua:439: in function <...vinb/.local/share/nvim/lazy/grapple.nvim/lua/grapple.lua:438>
```

Looking at the source code, `nvim-web-devicons` is a hard requirement, but I don't think it was mentioned anywhere in the README?

https://github.com/cbochs/grapple.nvim/blob/9c331b2f61cdfb747db1f322d9c47e0ca182e072/lua/grapple/tag_content.lua#L100-L103

I suppose one could either update the installation instructions to reflect this dependency, or make it an optional dependency and add a note on that in the README. _Although, this made me discover how nice these icons actually are within neovim lol_

**Comment by cbochs** [comment]
Thanks for pointing this out! I've gone ahead and updated the README to mention this

**Comment by cbochs** [comment]
@niveK77pur Just wanted to mention one thing quickly. nvim-web-devicons is not a hard requirement. You can disable icons in the settings, if you would like with

```
icons = false
```

But I'm glad to hear you are liking the icons so far 🙂
